name: example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_spine:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/raptor/raptor.atlas
    - assets/raptor/raptor.json
    - assets/raptor/raptor.png
    - assets/spineboy/spineboy.atlas
    - assets/spineboy/spineboy.json
    - assets/spineboy/spineboy.png
