name: example
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  spine_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/raptor/raptor.atlas
    - assets/raptor/raptor.json
    - assets/raptor/raptor.png
    - assets/spineboy/spineboy.atlas
    - assets/spineboy/spineboy.json
    - assets/spineboy/spineboy.png
